### ISSUE TITLE
Form refactor: improve error message when wrong API provided to submit

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_phoenix#10]
Minor DX improvement, when providing the wrong API to submit, currently getting:

```
** (BadMapError) expected a map, got: nil
    (ash_phoenix 0.4.23-rc.1) lib/ash_phoenix/form/form.ex:698: AshPhoenix.Form.submit/3
    (crm 0.1.0) lib/crm_web/live/profile_live.ex:83: CrmWeb.ProfileLive.handle_event/3
```

**Comment by zachdaniel** [comment]
<img width="831" alt="CleanShot 2021-07-18 at 12 47 33@2x" src="https://user-images.githubusercontent.com/5722339/126075446-8d4a17dd-0d5c-4756-a90b-664b26c94e7d.png">


Interesting, when I tested it I got this output

**Comment by zachdaniel** [comment]
If you can recreate w/ a test I will fix :)
