### ISSUE TITLE
Form refactor: validate_and_submit() helper

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_phoenix#11]
Minor DX improvement? I'm going to be doing a lot of this:

```elixir
  def handle_event("submit", %{"form" => params}, socket) do
    form = AshPhoenix.Form.validate(socket.assigns.form, params)
    case AshPhoenix.Form.submit(form, Crm.Accounts) do
      {:ok, _} ->
      ...
    end
  end
```

when i could:

```elixir
  def handle_event("submit", %{"form" => params}, socket) do
    case AshPhoenix.Form.validate_and_submit(socket.assigns.form, params, Crm.Accounts) do
      {:ok, _} ->
      ...
    end
  end
```

I can't think of a reason why I'd need to do something with the validated form before passing to submit? But if i do, i still can. Unless I'm doing it wrong in the first place? Of course i could implement my own helper

**Comment by totaltrash** [comment]
Feel free to delete this, it gets complicated with the opts to each function, so probably better to implement something opinionated in the application

**Comment by zachdaniel** [comment]
I've altered the behavior (and documentation) of the `params` option to `submit`.

So now it would look like:

```elixir
def handle_event("submit", %{"form" => params}, socket) do
  case AshPhoenix.Form.validate(socket.assigns.form, Crm.Accounts, params: params) do
    {:ok, _} ->
    ...
  end
end
```
