### ISSUE TITLE
mix ash_phoenix.gen.live doesn't add fields to show.ex

### ISSUE THREAD

**Issue by jarlah** [ash-project/ash_phoenix#117]
**Describe the bug**
mix ash_phoenix.gen.live doesn't add fields to show.ex, but they are added to form_component.ex and index.ex

**To Reproduce**
`mix ash_phoenix.gen.live AshActivityPlanner.Planner AshActivityPlanner.Planner.Participant`

in 

https://github.com/jarlah/ash-activity-planner

(which will ofc now overwrite the existing live view

**Expected behavior**
Fields should also be added to show.ex, as I have modified it after running the generator in https://github.com/jarlah/ash-activity-planner/blob/main/lib/ash_activity_planner_web/live/participant_live/show.ex#L18

**Additional context**

Forum discussion:

https://elixirforum.com/t/how-to-convert-mix-gen-live-to-ash-compatible-live-view/59785

**Comment by zachdaniel** [comment]
Thanks for the report! I won't have time to get to this soon likely, but it should be a pretty straight-forward thing to add. Marked as good first issue.

**Comment by jarlah** [comment]
@zachdaniel I see for gen.html it has this block of code in `priv/templates/ash_phoenix.gen.html/show.html.heex`:

```elixir
<.list>
<%= for attribute <- @attributes do %>
  <:item title="<%= Phoenix.Naming.humanize(attribute.name) %>"><%%= @<%= @singular %>.<%= attribute.name %> %></:item>
<% end %>
</.list>
```

however in `priv/templates/ash_phoenix.gen.live/show.ex.eex` it doesn't 

Also it's a bit unknown to me why the file extensions is so different. But I guess that's not important.

The important bit is if I can just add some similar block in code for listing the items?

**Comment by zachdaniel** [comment]
I think that file extension is wrong, but it's not really that important. We should fix it at some point though. Thanks for the issue and the fix!
