### ISSUE TITLE
Support phoenix_html 4.0 on new phoenix apps

### ISSUE THREAD

**Issue by jamilabreu** [ash-project/ash_phoenix#124]
> Because your app depends on ash_phoenix ~> 1.2 which depends on phoenix_html ~> 2.14 or ~> 3.0, phoenix_html ~> 2.14 or ~> 3.0 is required.

**Comment by zachdaniel** [comment]
I imagine there won't be any compatible issues. Would you like to PR bumping that dependency? We'll want to make sure that our dependency says `~> 3.0 or ~> 4.0` for backwards compatibility.
