### ISSUE TITLE
`AshPhoenix.Form.value` returns the `string` value of the field instead of the `boolean` type.

### ISSUE THREAD

**Issue by ostatni5** [ash-project/ash_phoenix#138]
**Describe the bug**
`AshPhoenix.Form.value` returns the `string` value of the field instead of the `boolean` type.
When the form is changed and the value of the field is the same as the initial.

**To Reproduce**

1. The update Ash form is created from the resource with the field `:enabled` set to `false` function
`AshPhoenix.Form.value` return correctly returns `false`.
2. User changes the value to `true` `AshPhoenix.Form.value` return correctly returns `true`.
3. User again changes the value to `false` `AshPhoenix.Form.value` return returns `"false"`.

https://github.com/ash-project/ash_phoenix/assets/26521377/f9ba5ba6-dc45-4833-9895-4eaf207857fe

```ex
defmodule HelloWeb.Post do
  use Ash.Resource

  actions do
    defaults([:create, :read, :update, :destroy])
  end

  attributes do
    uuid_primary_key(:id)

    attribute(:enabled, :boolean)
  end
end

defmodule HelloWeb.PostsLive do
  use HelloWeb, :live_view
  alias HelloWeb.Post

  def render(assigns) do
    ~H"""
    <.form :let={f} for={@form} phx-change="change">
      <.input type="checkbox" field={f[:enabled]}  />
      <%= inspect(AshPhoenix.Form.value(@form, :enabled)) %>
    </.form>
    """
  end

  def mount(_params, _session, socket) do
    socket =
      assign(socket,
        form:
          AshPhoenix.Form.for_update(%Post{enabled: false}, :update)
          |> to_form()
      )

    {:ok, socket}
  end

  def handle_event("change", %{"form" => params}, socket) do
    form =
      AshPhoenix.Form.validate(
        socket.assigns.form,
        Map.merge(socket.assigns.form.params, params)
      )

    IO.inspect(AshPhoenix.Form.value(form, :enabled), label: "enabled")

    {:noreply, assign(socket, :form, form)}
  end
end
```

**Expected behavior**
Return the same value for the field not depending on whether the form was edited or is untouched. 

**Runtime**
 - Elixir 1.14.3-otp-25
 - Erlang 26.1.2
 - Mac Os 14.2.1 
 - Ash 2.19.14
 - Ash phoenix 1.3

**Comment by zachdaniel** [comment]
🤔 interesting. What does `form.source.source.attributes` show after you validate it? Also, you shouldn't need to do `Map.merge(socket.assigns.form.params, params)`. The params object given contains all the params.

**Comment by ostatni5** [comment]
Inspect lines:
```ex
 IO.inspect(form.source.source.attributes, label: "form.source.source.attributes")

IO.inspect(AshPhoenix.Form.value(form, :enabled), label: "enabled")
```

Result:

```
[debug] HANDLE EVENT "change" in HelloWeb.PostsLive
  Parameters: %{"_target" => ["form", "enabled"], "form" => %{"enabled" => "true"}}
form.source.source.attributes: %{enabled: true}
enabled: true
[debug] Replied in 14ms
[debug] HANDLE EVENT "change" in HelloWeb.PostsLive
  Parameters: %{"_target" => ["form", "enabled"], "form" => %{"enabled" => "false"}}
form.source.source.attributes: %{}
enabled: "false"
```

**Comment by zachdaniel** [comment]
Thanks for the report, this is fixed. Requires using the latest version of `ash_phoenix` *and* `ash`.

**Comment by zachdaniel** [comment]
Actually, still a few kinks to work out :)

**Comment by zachdaniel** [comment]
`1.3.4` is releasing in CI w/ these fixes.
