### ISSUE TITLE
Latest version `1.3.2` of Ash Phoenix depends on Ash version `~> 2.16.1` with known bug

### ISSUE THREAD

**Issue by jakeschurch** [ash-project/ash_phoenix#139]
**Describe the bug**

Required version of latest ash phoenix release `1.3.2` requires ash version with (upstream fixed) bug that ensures that "If the aggregated resource has a default preparation that will load other resources, the aggregation will fail". See [Ash issue #806](https://github.com/ash-project/ash/issues/806)

**To Reproduce**
Have following in mix.exs's deps, and try to load multiple aggregates, follow [Ash issue #806](https://github.com/ash-project/ash/issues/806) to reproduce.

```
{:ash, "~> 2.16.1"},
{:ash_phoenix, "~> 1.3.2"},
```

**Expected behavior**

**Runtime**
 - Elixir version `1.15.7`
 - Erlang version `25`
 - OS `darwin`  
 - Ash version `2.16.1`
 - any related extension versions phoenix `1.3.2`

**Comment by zachdaniel** [comment]
`1.3.3` is out with looser version requirements. Thanks for the report :)
