### ISSUE TITLE
doc: pre-3.0 section in Ash Phoenix documentation

### ISSUE THREAD

**Issue by BartOtten** [ash-project/ash_phoenix#161]
"some config for backwards compatibility that will be removed in the next major release." seems to be about... right now.

https://github.com/ash-project/ash_phoenix/blob/832c10c870e225031629d801ce15a000218f267a/documentation/tutorials/getting-started-with-ash-and-phoenix.md?plain=1#L115

ps. Thanks for Ash!

**Comment by zachdaniel** [comment]
Changed :)
