### ISSUE TITLE
Allow Phoenix LiveView 1.0-rc

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_phoenix#190]
The current `mix.exs` only permits LV 0.20.x, and now 1.0-rc is out.

There's [only one breaking change](https://github.com/phoenixframework/phoenix_live_view/blob/main/CHANGELOG.md#backwards-incompatible-changes-for-10) for LV 1.0-rc, and it doesn't affect anything AshPhoenix does - only how errors should be rendered in a form.

From my testing (adding LV 1.0-rc with `override: true`) there should be no issues with loosening the version restriction to support 1.0-rc (and then probably 1.0.x).

**Comment by zachdaniel** [comment]
So I haven't allowed for the release candidate, but I did allow for 1.0. This at least signals to folks that we're compatible, and when its out of release candidacy folks can upgrade without `override: true`
