### ISSUE TITLE
Regression in 0.4.19

### ISSUE THREAD

**Issue by axelson** [ash-project/ash_phoenix#2]
We discussed in discord (https://discord.com/channels/711271361523351632/799097774523547669/853717356865519648) that 0.4.19 appears to cause a regression in the `add_to_path` logic

You can easily see the failing test from my private repo https://github.com/axelson/gen_tracker/tree/broken-ash-phoenix-0.4.19 (note the tag)
by running the seed script and then visiting an item (i.e. http://localhost:4000/item/1) and pressing "add track"

**Comment by zachdaniel** [comment]
Form logic is being completely rewritten to a dedicated data structure, `AshPhoenix.Form`. This should be released soon.
