### ISSUE TITLE
Error on submit when removing the last item from a nested resource 

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_phoenix#21]
See test case in #20 

C&P from discord:

whenever we remove a form, we just track the path we're removing e.g

```elixir
%Form{
  removed_paths: [
    [:comments, 0, :post],
    [:post, :comments, 0]
  ]
}
```

and then when we create a form we just traverse all the forms and their data and remove those things
Yeah, thats what we'll have to do

dblack — Today at 16:19

uh, say i remove a form, then add a form, then remove a form... will that all fall over as the new form might get blown away on validate by the list of removed_paths.

ZachDaniel — Today at 16:19

No, that should be fine

dblack — Today at 16:20

cool

ZachDaniel — Today at 16:20

because when we handle these removed_paths, we're only going to remove the data that backs them
like if you had data like post: [comment, comment, comment]
if you remove `[:post, :comments, 0]` we also get the data for that form, and remove the 0th thing
and thats effectively "permanent"

**Comment by zachdaniel** [comment]
Fixed!
