### ISSUE TITLE
Provide `AshPhoenix.Type.Upload` to wrap `Plug.Upload`

### ISSUE THREAD

**Issue by maennchen** [ash-project/ash_phoenix#226]
**Is your feature request related to a problem? Please describe.**

I would like to accept file uploads as arguments to actions. (Use case: bulk import of records)

**Describe the solution you'd like**

* Create `AshPhoenix.Type.Upload`
* Accept `%Plug.Upload{...}` (for usage in phoenix forms and `ash_json_api`)
* Wrap `%{path: string}` (for usage in live view forms, see [`Phoenix.LiveView.UploadTmpFileWriter.meta/1`](https://github.com/phoenixframework/phoenix_live_view/blob/fa277d35242def04a0c9fc39217fcd179e5539c1/lib/phoenix_live_view/upload_tmp_file_writer.ex#L16))
* Possibly implement form attribute field in `ash_admin`

**Describe alternatives you've considered**

```elixir
attributes do
  attribute :file, :struct, constraints: [instance_of: Plug.Upload]
end
```

This however makes it hard to support across the ecosystem like in the `ash_admin` forms.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

For example

```elixir
  attributes do
    attribute :file, AshPhoenix.Type.Upload
  end
```

**Additional context**

None

**Comment by zachdaniel** [comment]
We're definitely interested in exploring the file upload space as a general set of tooling, this could be a great start to that. 

I think the main thing, however, is that the file type be agnostic of `AshPhoenix`, perhaps even living in core. i.e `Ash.Type.File`, or `AshFiles.Types.File` etc.

**Comment by maennchen** [comment]
@zachdaniel How would you approach this since there's lots of representations for files / uploads?

* path - `string`
* upload - `Plug.Upload`
* live view upload (tmp writer) - `map`
* anything compatible to `IO.device()`
* ...

One option could be to provide a protocol that has to yield a path.

**Comment by zachdaniel** [comment]
Its hard to say w/o diving in, but a protocol could potentially be a limiting design choice in this case, given that we aren't in control of how people choose to represent files going forward. We'd probably have an `%Ash.File{}` struct that can wrap any given source, i.e `%Ash.File{source: %Plug.Upload{}, impl: Ash.File.PlugUpload}`, where there is a behavior for `Ash.PlugUpload`. Then a protocol can be implemented that turns a `%Plug.Upload{}` into an `%Ash.File{}`, but you can also explicitly create one for a map. 

`AshPhoenix` would then be enriched to have built-in handling for phoenix's types, as would things like `AshJsonApi` and `AshGraphql` to allow for uploads in whatever way is idiomatic for the interface in question.

**Comment by maennchen** [comment]
Resolved by PR
