### ISSUE TITLE
Extend FilterForm to support TSQuery/TSVector Types

### ISSUE THREAD

**Issue by allenwyma** [ash-project/ash_phoenix#241]
**Is your feature request related to a problem? Please describe.**
The FilterForm works great for most usecases, but I'd like to have it extendable, so we can add in new types. Most users, today, just expect to have minimal inputs and a single "search bar" that will span across multiple fields. Postgres comes with full text search which can make the process more suitable for searching/filtering text fields.

**Describe the solution you'd like**
I'd like to have it so i can send over more customized operators:
`:"@@"` and also I can define what the filtering would work like, like with full text search, i believe the style would be "FIELD @@ websearch_to_tsquery(VALUE)", so if we can somehow setup the query to work like that. Maybe we can pass in a fragment template or something?

**Describe alternatives you've considered**
otherwise, i may consider to handle this outside of filterform, but then this leave filterform only able to support the basic types.

**Additional context**

**Comment by allenwyma** [comment]
Some links provided by a core team member: barnabasj:

https://github.com/ash-project/ash_hq/blob/146e0559687463751ed8e7f2cdb50a133cc510ae/lib/ash_hq/docs/extensions/search/transformers/add_search_structure.ex
https://github.com/ash-project/ash_hq/blob/146e0559687463751ed8e7f2cdb50a133cc510ae/lib/ash_hq/docs/extensions/search/transformers/add_search_structure.ex

**Comment by zachdaniel** [comment]
This type of thing can be accomplished with calculations typically.

i.e

```elixir
calculation :matches_search?, :boolean, expr(fragment("...")) do
  argument :query, :string, allow_nil?: false
end
```

Have you tried that approach?

As for being able to customize operators, you can do that with `Ash.CustomExpression`, that has `predicate?: true` defined in its options. But I think the calculation approach ought to be the way. If you can't find a way to do it w/ calculations, then we can reopen this issue, but will need to have a slightly more specific proposal of how to accomplish the task.

**Comment by allenwyma** [comment]
Just got around to checking this out, now. Let me know if I'm doing something wrong, but from what I see, I believe that the to_filter_map may have a bug with arguments. Here's what I've managed to create:

Calculation:
```elixir
calculations do
    calculate :text_search, :boolean, expr(fragment("(? @@ websearch_to_tsquery(?))")) do
      argument :query, :string, allow_nil?: false
      public? true
    end
  end
```

Helper function with going from url params to a filter:
```elixir
@spec to_filter(Keyword.t(), map(), Ash.Resource.t()) :: Keyword.t()
  def to_filter(page_params, params, resource) do
    with %{} = filter_params <- params["filter"] |> IO.inspect(label: "params"),
         form <- FilterForm.new(resource, params: filter_params) |> IO.inspect(label: "form"),
         {:ok, filter_map} <- FilterForm.to_filter_map(form) |> IO.inspect(label: "map"),
         {:ok, filter} <- Ash.Filter.parse(resource, filter_map) do
      Keyword.put(page_params, :filter, filter)
    else
      {:error, invalid} ->
        IO.inspect(invalid, label: "invalid")
        page_params

      nil ->
        page_params
    end
  end
```

Logs:
```
params: %{
  "components" => %{
    "0" => %{
      "_persistent_id" => "0",
      "arguments" => %{"_persistent_id" => "0", "query" => "test"},
      "field" => "text_search",
      "id" => "2bca35b4-6d2a-4292-967c-c919620b9fb3",
      "operator" => "eq",
      "value" => ""
    }
  },
  "operator" => "and"
}
form: %AshPhoenix.FilterForm{
  id: "866bd1d8-520a-4742-90ba-2b8537f012fc",
  resource: App.Accounts.User,
  transform_errors: nil,
  name: "filter",
  valid?: true,
  negated?: false,
  params: %{
    "components" => %{
      "0" => %{
        "arguments" => %{"_persistent_id" => "0", "query" => "test"},
        "field" => "text_search",
        "id" => "2bca35b4-6d2a-4292-967c-c919620b9fb3",
        "negated" => false,
        "operator" => "eq",
        "path" => nil,
        "value" => ""
      }
    },
    "id" => "866bd1d8-520a-4742-90ba-2b8537f012fc",
    "negated" => false,
    "operator" => "and"
  },
  components: [
    %AshPhoenix.FilterForm.Predicate{
      id: "2bca35b4-6d2a-4292-967c-c919620b9fb3",
      field: :text_search,
      value: "",
      transform_errors: nil,
      operator: :eq,
      params: %{
        "arguments" => %{"_persistent_id" => "0", "query" => "test"},
        "field" => "text_search",
        "id" => "2bca35b4-6d2a-4292-967c-c919620b9fb3",
        "negated" => false,
        "operator" => "eq",
        "path" => nil,
        "value" => ""
      },
      arguments: %AshPhoenix.FilterForm.Arguments{
        input: %{query: "test"},
        params: %{"_persistent_id" => "0", "query" => "test"},
        arguments: [
          %Ash.Resource.Calculation.Argument{
            allow_nil?: false,
            allow_expr?: false,
            constraints: [trim?: true, allow_empty?: false],
            default: nil,
            name: :query,
            type: Ash.Type.String
          }
        ],
        errors: []
      },
      negated?: false,
      path: [],
      errors: [],
      valid?: true
    }
  ],
  operator: :and,
  remove_empty_groups?: false
}
map: {:ok, %{"and" => [%{"text_search" => %{"eq" => ""}}]}}
invalid: %Ash.Error.Query.InvalidCalculationArgument{
  calculation: :text_search,
  field: :query,
  message: "is required",
  value: nil,
  splode: nil,
  bread_crumbs: [],
  vars: [],
  path: [],
  stacktrace: #Splode.Stacktrace<>,
  class: :invalid
}
params: [offset: 0, limit: 20]
```

Based on the above, it looks like the `AshPhoenix.FilterForm.to_filter_map/1` seems to be removing the arguments.

For context, I had to create a new box just for this and it's a text box, and i've entered in just "text".

**Comment by zachdaniel** [comment]
I have the error reproduced

**Comment by allenwyma** [comment]
I'm still not getting this to work:

```
filter: %{
  "components" => %{
    "0" => %{
      "_persistent_id" => "0",
      "arguments" => %{"_persistent_id" => "0", "query" => "test"},
      "field" => "text_search",
      "id" => "b85c1ed0-f7f5-4d97-b8d6-5664a5959e8f",
      "path" => "",
      "value" => ""
    }
  },
  "operator" => "and"
}
invalid: %Ash.Error.Query.InvalidCalculationArgument{
  calculation: :text_search,
  field: :query,
  message: "is required",
  value: nil,
  splode: nil,
  bread_crumbs: [],
  vars: [],
  path: [],
  stacktrace: #Splode.Stacktrace<>,
  class: :invalid
}
```

The code above still is the same, the IO.inspect may have chagned, but the first is the arguments coming in, the params from the URL, and the bottom is the log for the `invalid` in the error tuple in the else section.

**Comment by allenwyma** [comment]
FYI: for history, this was solved after some private back and forth.
