### ISSUE TITLE
validate_opts on `add_form` and `remove_form`

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_phoenix#41]
**Describe the bug**
Thanks for adding the validate_opts to these two functions. They're not working though!

**To Reproduce**
Setting validate_opts like:

```elixir
form = AshPhoenix.Form.add_form(form, :nested, validate_opts: [errors: false])
```
is hiding errors on the outer form, but not for the `:nested` form

**Expected behavior**
both the outer and nested forms to have errors hidden/not populated on the form, when setting `validate_opts: [errors: false]`

** Runtime
 - Elixir version
 - Erlang version
 - OS
 - Ash version: main
 - any related extension versions

**Additional context**

**Comment by totaltrash** [comment]
Hey Zach, I'm still seeing this as an issue

**Comment by zachdaniel** [comment]
I'll take a look at this in the morning. If you have some time to put up a failing test that would be great :)
