### ISSUE TITLE
Protocol Phoenix.HTML.FormData not implemented for #Ash.Changeset

### ISSUE THREAD

**Issue by don-mums** [ash-project/ash_phoenix#49]
**Describe the bug**
I'm creating login where I try to `mix phx.gen.auth` and [example_with_auth](https://github.com/ash-project/example_with_auth). I hit this bug which prevents me from rendering forms.

**To Reproduce**
Create 
This throws error above:
`<.form let={f} for={@changeset} action={Routes.accounts_user_registration_path(@conn, :create)}>`
eex equivalent: `<%= form_for @changeset, Routes.accounts_user_registration_path(@conn, :create), fn f -> %>`

When changing `changeset` for `:user` form works but is pretty much useless.
`<.form let={f} for={:user} action={Routes.accounts_user_registration_path(@conn, :create)}>`
eex equivalent: `<%= form_for :user, Routes.accounts_user_registration_path(@conn, :create), fn f -> %>`
Both heex and eex cause this bug.

**Expected behavior**
Form to be rendered into HTML.

** Runtime
I tried also latest master of ash and ash_phoenix with the same result.

 - Elixir version: 1.13.0
 - Erlang version: Erlang/OTP 25
 - OS: Ubuntu LTS 20.04
 - Ash version: 1.51.2
 - Ash_Phoenix: 0.7.1
 - Phoenix; 1.6.10
 - Phoenix_HTML: 3.2.0

**Additional context**
Maybe I'm using too complex forms here but I doubt it. My code is basically the same as [user_registration_controller.ex](https://github.com/ash-project/example_with_auth/blob/main/lib/example_with_auth_web/controllers/user_registration_controller.ex) and [new.html.eex](https://github.com/ash-project/example_with_auth/blob/main/lib/example_with_auth_web/templates/user_registration/new.html.eex).

If you need access to code you can look [on my GitLab](https://gitlab.com/don-mums/shortly/-/tree/update2). Prepare for mid upgrade mess on a small toy project with no tests. Just try to register. Oh and use env variables from `.envrc.tmpl` to get it up and running.
Url to trigger bug: http://localhost:4000/accounts/users/register

As you can tell I wasn't expecting someone else to use that code for anything. But I'm happy to test any changes that might help solve the issue.

**Comment by zachdaniel** [comment]
Hey there! So unfortunately, the `example_with_auth` project is pretty out of date. What you need to do is create an `AshPhoenix.Form` for the changeset, and assign that. Then, to submit it, you'd create a form again, validate it with the input, and then submit it. Check out `AshPhoenix.Form` for more information and examples. In the case of user registration, it would end up looking something like this:

```elixir
defmodule ExampleWithAuthWeb.UserRegistrationController do
  use ExampleWithAuthWeb, :controller

  alias ExampleWithAuth.Accounts
  alias ExampleWithAuth.Accounts.User
  alias ExampleWithAuthWeb.UserAuth

  def new(conn, _params) do
    form = AshPhoenix.Form.for_create(User, :register)

    render(conn, "new.html", form: form)
  end

  def create(conn, %{"user" => user_params}) do
    User
    |> AshPhoenix.Form.for_create(:register)
    # You could call `AshPhoenix.Form.validate/2` here, but passing `params` into submit does it for you
    |> AshPhoenix.Form.submit(params: user_params, api: Accounts)
    |> case do
      {:ok, user} ->
        user
        |> Ash.Changeset.for_update(:deliver_user_confirmation_instructions, %{
          confirmation_url_fun: &Routes.user_confirmation_url(conn, :confirm, &1)
        })
        |> Accounts.Api.update!()
        
        
        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)
      {:error, form} ->
        render(conn, "new.html", form: form)
    end
  end
end
```

**Comment by zachdaniel** [comment]
Closing for now since there isn't a specific action to be taken for this, but feel free to continue discussing here or on the discord 👍🏻

**Comment by zachdaniel** [comment]
I'll also add, I'm working on fully revamping the documentation, and given that people are still consulting `example_with_auth`, I'll consider updating it since that would be much faster than waiting on `ash_authentication` to happen.

**Comment by don-mums** [comment]
@KronicDeth on Elixirconf EU told me about this project and auto-generated admin. I was warned that docs are not good. I'm glad you take these things seriously.

**Comment by zachdaniel** [comment]
Correct, the documentation has not been the focus as the project is still in beta. It will be taken out of beta in the near future once the documentation has been fully rebuilt.
