### ISSUE TITLE
AshPhoenix.Form needs some way of maintaining order of nested records

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_phoenix#57]
**Is your feature request related to a problem? Please describe.**

As discussed earlier. If we - 

* show a form with nested data, eg. Element with many ToolSpecifications
* save the form successfully, which returns the updated Element
* reload the Element + nested data
* rebuild the form with the reloaded data

The nested records might not be in the same order as on the original form, thus re-rendering the page would have the nested records re-ordering and shifting on the page.

Even if we sort forms in the view, with something like 

```elixir
Enum.sort_by(inputs_for(@form, :tool_specifications), & Form.value(&1, :inserted_at))
```

Nested records may have been created at the same time, so the `inserted_at` timestamps will be the same and thus fall back to the database default ordering. Correct sorting of timestamps also needs an extra argument like `{:asc, DateTime}` to be passed to `Enum.sort_by/3`, which will then fail when new nested records are built (because the timestamps will be not be set).

And if a field in the nested form is focussed at the time of save - Phoenix won't change the value of any focussed field, even though the value underlying it may change. So eg. 

* editing Quantity of nested tool specification 1
* save form with Quantity field still in focus
* Tool specification 1 is now end of the list of loaded tool specifications
* First nested form still shows with the entered Quantity even though the underlying record has changed, so it looks like two records now have the data when you only updated one.

(That may be more of an edge case for my project as we have keyboard shortcuts for saving, instead of a submit button)

**Describe the solution you'd like**

A way to take a new form, and an old form, and tell the new form to use the order of nested records from the old form.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

Possibly something like:

```elixir 
Form.for_update(element, :update, api: MyApp.Api, forms: [auto?: true]
|> Form.reorder_nested(previous_form)
```

That would then iterate over the nested data and make sure ordering in the new form matches the old form.

**Comment by zachdaniel** [comment]
So after thinking about this a bit more, I think the actual answer here is for the data to come back from the action with the resulting relationship loaded, and already sorted. This would only work in some cases, specifically when the entire relationship needs to be loaded, or in cases where we are performing a create action and are creating related records. However, if you aren't in one of those cases, you almost certainly aren't expecting to save the form and then get records back in the same order anyway, because if you load the relationship you'll get more than you sent back. So the pattern would look something like this:
```elixir
case Form.submit(form) do
  {:ok, result} ->
     assign_form(socket, result)
   {:error, form} ->
     assign(socket, :form, form)
end

...

defp assign_form(socket, thing_you_are_updating) do
  thing_you_are_updating
  |> Api.load!([relationship: :foo], lazy?: true) # the `lazy?: true` will keep anything that is already loaded, and the edited relationship will be loaded as a result of the action
  |> AshPhoenix.Form.for_update(...)
end
```

**Comment by zachdaniel** [comment]
Actually...looks like we're already doing this in core :) @sevenseacat perhaps you could try using a `lazy?: true` load as illustrated above and see if that works for you?

**Comment by sevenseacat** [comment]
Originally the reason I was reloading all of the data was because relationships weren't coming back on the record after update, meaning re-rendering the form was erroring - that doesn't seem to happen anymore which is good! I can remove that reloading-data loop entirely.

However, the data is still being returned by the action in a different order.

eg.

```elixir
    dbg(AshPhoenix.Form.value(socket.assigns.element_form, :tool_specifications))
    dbg(params)

    case AshPhoenix.Form.submit(socket.assigns.element_form, params: params) do
      {:ok, updated_element} ->
        dbg(updated_element.tool_specifications)
```

gives:

```elixir
AshPhoenix.Form.value(socket.assigns.element_form, :tool_specifications) #=> [
  %{
    "_form_type" => "update",
    "id" => "abdab2a1-a221-43fe-be50-1add1a40cf8f",
    "quantity" => "1431",
    "specification_id" => "ea9544d9-5d5a-4014-9a59-335719bcd2ea",
  },
  %{
    "_form_type" => "update",
    "id" => "a3bc5d69-b683-4e42-83df-9a24eb9a2881",
    "quantity" => "21",
    "specification_id" => "022e2e06-fbe9-41d9-9860-4d67ca8a73c0",
  }
]

params #=> %{
  # other stuff
  "tool_specifications" => %{
    "0" => %{
      "_form_type" => "update",
      "_touched" => "_form_type,id,quantity,specification_id",
      "id" => "abdab2a1-a221-43fe-be50-1add1a40cf8f",
      "quantity" => "1431",
      "specification_id" => "ea9544d9-5d5a-4014-9a59-335719bcd2ea",
    },
    "1" => %{
      "_form_type" => "update",
      "_touched" => "_form_type,id,quantity,specification_id",
      "id" => "a3bc5d69-b683-4e42-83df-9a24eb9a2881",
      "quantity" => "21",
      "specification_id" => "022e2e06-fbe9-41d9-9860-4d67ca8a73c0",
    }
  }
}

updated_element.tool_specifications #=> [
  #MyApp.Element.ToolSpecification<
    specification: #MyApp.Tool.Specification<>,
    __meta__: #Ecto.Schema.Metadata<:loaded, "element_tool_specifications">,
    id: "a3bc5d69-b683-4e42-83df-9a24eb9a2881",
    quantity: 21,
    inserted_at: ~U[2022-10-17 06:16:24.635005Z],
    updated_at: ~U[2022-10-19 01:12:37.432723Z],
    element_id: "a8316188-2fe2-4ddb-a9b4-e02cb209bbac",
    specification_id: "022e2e06-fbe9-41d9-9860-4d67ca8a73c0",
    aggregates: %{},
    calculations: %{},
    __order__: nil,
    ...
  >,
  #MyApp.Element.ToolSpecification<
    specification: #MyApp.Tool.Specification<>,
    element: #Ash.NotLoaded<:relationship>,
    __meta__: #Ecto.Schema.Metadata<:loaded, "element_tool_specifications">,
    id: "abdab2a1-a221-43fe-be50-1add1a40cf8f",
    quantity: 1431,
    inserted_at: ~U[2022-10-17 05:53:26.206812Z],
    updated_at: ~U[2022-10-19 01:13:16.172939Z],
    element_id: "a8316188-2fe2-4ddb-a9b4-e02cb209bbac",
    specification_id: "ea9544d9-5d5a-4014-9a59-335719bcd2ea",
    aggregates: %{},
    calculations: %{},
    __order__: nil,
    ...
  >
]
```

**Comment by zachdaniel** [comment]
Okay, yeah I can see that. I guess the current behavior just doesn't do the work to preserve order. I'll take a look in the morning.

**Comment by zachdaniel** [comment]
I'm actually pretty sure its just reversing the inputs, because as we apply the inputs we do things like `[result | relationship_value]`. So I'll toss in an `Enum.reverse` in and I think we'll be good :)

**Comment by zachdaniel** [comment]
Alright, so the fix for this *should* be in `main`. Anyone else looking: if you are loading data after submitting a form, you will want to use `lazy?: true` so as not to potentially reorder the relationship after editing it.

**Comment by zachdaniel** [comment]
@sevenseacat feel free to reopen if you see more issues along these lines.
