### ISSUE TITLE
Documentation Example Error

### ISSUE THREAD

**Issue by kingdomcoding** [ash-project/ash_phoenix#61]
This example appears on ash-hq:

https://github.com/ash-project/ash_phoenix/blob/1e5f344215c2d15f458e673fc522312efb0e0234/lib/ash_phoenix/form/form.ex#L109-L126

Note that the action parameter is missing. Is it supposed to be?

**Comment by zachdaniel** [comment]
Definitely not intentional :) Would you want to PR a fix?

**Comment by kevinam99** [comment]
Fixed in https://github.com/ash-project/ash_phoenix/pull/85
