### ISSUE TITLE
Missing logo file causes `mix doc` to fail.

### ISSUE THREAD

**Issue by brunoripa** [ash-project/ash_phoenix#64]
**Describe the bug**
Building the documentation by running `mix doc` fails because in `mix.exs` file a non-existing  "logos/small-logo.png"

**To Reproduce**
Just checkout the repo and build docs.

**Expected behavior**

The doc creation should produce the result in the `docs` folder.

** Runtime
 - Elixir version: 1.14.2
 - Erlang version: 25
 - OS: Win 11 (WSL2)
 - Ash version: 2.4.28

I can PR a fix which deletes the logo or can fix it if I get the logo which is intended to be used.

**Comment by zachdaniel** [comment]
🤔 it works for me...
