### ISSUE TITLE
Broken "philosophy" link  in https://github.com/ash-project/ash_phoenix/blob/v1.2.10/documentation/tutorials/getting-started-with-ash-and-phoenix.md

### ISSUE THREAD

**Issue by rsieb** [ash-project/ash_phoenix#80]
in https://github.com/ash-project/ash_phoenix/blob/v1.2.10/documentation/tutorials/getting-started-with-ash-and-phoenix.md

**Describe the bug**
"- [Philosophy Guide](/documentation/tutorials/philosophy.md)"
results in a broken link

**Expected behavior**
"- [Philosophy Guide](https://ash-hq.org/docs/guides/ash/latest/tutorials/philosophy)"
leads to (probably?) the right document

**Comment by rsieb** [comment]
in https://github.com/ash-project/ash_phoenix/blob/v1.2.10/documentation/tutorials/getting-started-with-ash-and-phoenix.md

**Comment by zachdaniel** [comment]
Thanks for the report! I've fixed the issue in main, and on the next release of `ash_phoenix` it will be re-released.
